// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The `vnc` plugin's OWN CUE schema — the typed plugin_input for the `vnc`
// RFB/VNC check verb. It is the SINGLE SOURCE for this plugin's params, used two
// ways (the same contract core `spec` and the http plugin use):
//
//  1. GENERATE the Go param struct — `cue exp gengotypes` (driven by the cue:gen
//     pipeline, which wraps this with `package params` + `@go(params)`) emits
//     ../params/cue_types_gen.go, so the provider decodes plugin_input into a
//     TYPED struct, never a hand-parsed map.
//  2. VALIDATE authored input AT RUNTIME — the plugin serves this source over the
//     Describe channel; the host splices it onto the base (base ++ plugin) and
//     validates every authored `vnc:` step's plugin_input against #VncInput.
//
// Since the schema-compaction cutover the per-verb fields LEFT core #Op: an
// authored `vnc: <method>` step (scalar sugar) or `vnc: {method: …, x: …}` (map
// form) desugars to the INTERNAL plugin/plugin_input envelope, and every
// vnc-exclusive modifier lives HERE — the former core #VncMethod enum is this
// def's `method` field, and the former shared #Op `method` modifier (which `rfb`
// used for the raw RFB sub-method) is RENAMED `http_method` (the input's
// `method` key is the VERB method), mirroring the cdp `raw` rename. The shared
// assertion matchers (exit_status/stdout/stderr) and the general `timeout` stay
// on core #Op, read off the step Op by the provider.
//
// SELF-CONTAINED: it references NO base def, so it compiles standalone
// (gengotypes + the load-gate compile) AND splices onto the base (base ++ plugin
// is a def-name collision check, not a base-reference resolver).
type VncInput struct {
	// method — the vnc method to dispatch (the former core #VncMethod enum; also
	// the scalar-sugar primary: `vnc: <method>`).
	Method string `yaml:"method,omitempty" json:"method"`

	// action — start|stop|status for a session (session). session start begins
	// capturing the RFB framebuffer at fps into an MJPEG stream (the host-side
	// detached recorder); session stop finalizes it to the evidence row.
	Action string `yaml:"action,omitempty" json:"action,omitempty"`

	// fps — the framebuffer capture rate for session (default 5).
	Fps int `yaml:"fps,omitempty" json:"fps,omitempty"`

	// x / y — desktop-absolute coordinates (click/mouse).
	X int `yaml:"x,omitempty" json:"x,omitempty"`

	Y int `yaml:"y,omitempty" json:"y,omitempty"`

	// button — the mouse button for click (left/right/middle; default left).
	Button string `yaml:"button,omitempty" json:"button,omitempty"`

	// text — the text `type` types.
	Text string `yaml:"text,omitempty" json:"text,omitempty"`

	// key — the named key `key` presses.
	KeyName string `yaml:"key,omitempty" json:"key,omitempty"`

	// http_method — the raw RFB sub-method `rfb` sends (key/pointer/cut-text/
	// fbupdate-request; RENAMED from the former shared #Op `method` modifier —
	// `method` here is the VERB method), mirroring the cdp `raw` rename.
	HttpMethod string `yaml:"http_method,omitempty" json:"http_method,omitempty"`

	// params — the JSON params blob `rfb` passes to the sub-method.
	Params string `yaml:"params,omitempty" json:"params,omitempty"`

	// artifact — the host path `screenshot` writes the PNG to.
	Artifact string `yaml:"artifact,omitempty" json:"artifact,omitempty"`

	// artifact_min_bytes / artifact_min_dimensions / artifact_not_uniform — the
	// post-run artifact-reality assertions (sdk.RunArtifactValidators).
	ArtifactMinBytes int `yaml:"artifact_min_bytes,omitempty" json:"artifact_min_bytes,omitempty"`

	ArtifactMinDimensions string `yaml:"artifact_min_dimensions,omitempty" json:"artifact_min_dimensions,omitempty"`

	ArtifactNotUniform bool `yaml:"artifact_not_uniform,omitempty" json:"artifact_not_uniform,omitempty"`

	// session — the DETACHED host-side recorder (Cutover E, E-1): `vnc: session` starts
	// the plugin's OWN binary in recorder mode through the runner's generic
	// background-session service (plugin-check's verb:session seam). The recorder
	// holds the RFB wire itself — the provider stays wire-free — polls the
	// framebuffer at fps into state_dir/frames.mjpeg, and on SIGTERM finalizes with
	// the FINAL marker + the evidence row.json. venue/phase are stamped into the
	// evidence row.
	SessionId string `yaml:"session_id,omitempty" json:"session_id,omitempty"`

	StateDir string `yaml:"state_dir,omitempty" json:"state_dir,omitempty"`

	// artifact_dir — the runner-injected generic evidence-artifact dir (verb-agnostic;
	// the provider appends its own filename/extension).
	ArtifactDir string `yaml:"artifact_dir,omitempty" json:"artifact_dir,omitempty"`

	LogDir string `yaml:"log_dir,omitempty" json:"log_dir,omitempty"`

	Venue string `yaml:"venue,omitempty" json:"venue,omitempty"`

	Phase string `yaml:"phase,omitempty" json:"phase,omitempty"`
}
